### PR TITLE
Fix key expired in get

### PR DESCRIPTION
**Pull request by hyzhangzhy**
#### Related changes (conditional)

- Tests
    - [ ] If I added new functionality, I added tests covering it.
    - [x] If I fixed a bug, I added a regression test to prevent the bug from
      silently reappearing again.

- Documentation
    - [x] I checked whether I should update the docs and did so if necessary:
        - [README](../README.md)

- Public contracts
    - [x] My changes doesn't break project license.

#### Stylistic guide (mandatory)

- [x] My code complies with the [styles guide](https://github.com/uber-go/guide/blob/master/style.md).
- [x] My commit history is clean (only contains changes relating to my
  issue/pull request and no reverted-my-earlier-commit changes) and commit
  messages start with identifiers of related issues in square brackets.

  **Example:** `[#42] Short commit description`

  If necessary both of these can be achieved even after the commits have been
  made/pushed using [rebase and squash](https://git-scm.com/docs/git-rebase).

#### Before merging (mandatory)
- [x] Check __target__  branch of PR is set correctly

### CODE REVIEW

**Comment by maypok86** [comment]
In fact, it is possible not to push the event at all and wait for proactive expiration, but the solution with immediate expiration is most likely a little more effective.

**Comment by hyzhangzhy** [comment]
Yes. 

I see you have written a timewheel go routinue for proactive expiration, if no get func is called it is expired correctly. But if get func is called, it will push a wrong event which need to fix.

**Comment by maypok86** [comment]
Okay, but I can't accept this without removing the node from the hash table.

**Comment by hyzhangzhy** [comment]
Oh, yes, it will never deleted...
and push again and again...

I think this is the right version.
```go
func (c *Cache[K, V]) GetNode(key K) (node.Node[K, V], bool) {
	n, ok := c.hashmap.Get(key)
	if !ok || !n.IsAlive() {
		c.stats.IncMisses()
		return nil, false
	}

	if n.HasExpired() {
                // avoid duplicate push
		deleted := c.hashmap.DeleteNode(n)
		if deleted != nil {
			n.Die()
			c.writeBuffer.Push(newExpiredTask(n))
		}
		c.stats.IncMisses()
		return nil, false
	}

	c.afterGet(n)
	c.stats.IncHits()

	return n, true
}
```

**Comment by hyzhangzhy** [comment]
Fixed.

**Comment by maypok86** [comment]
Thanks for the contribution!

**Pull request merged**
